version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"  # Map port 4000 on your machine to port 3000 in the container
    volumes:
      - .:/usr/src/app
